version: "3.8"
services:
  rabbitmq1:
    image: rabbitmq:3.13-management
    hostname: rabbit1
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_ERLANG_COOKIE='secretcookie'
    volumes:
      - ./rabbitmq1:/var/lib/rabbitmq
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - rabbitmq-net

  rabbitmq2:
    image: rabbitmq:3.13-management
    hostname: rabbit2
    environment:
      - RABBITMQ_ERLANG_COOKIE='secretcookie'
    volumes:
      - ./rabbitmq2:/var/lib/rabbitmq
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins
    depends_on:
      - rabbitmq1
    networks:
      - rabbitmq-net

  rabbitmq3:
    image: rabbitmq:3.13-management
    hostname: rabbit3
    environment:
      - RABBITMQ_ERLANG_COOKIE='secretcookie'
    volumes:
      - ./rabbitmq3:/var/lib/rabbitmq
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins
    depends_on:
      - rabbitmq1
    networks:
      - rabbitmq-net

  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - rabbitmq-net

  grafana:
    image: grafana/grafana:11.1.3
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge
