global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq1:15692", "rabbitmq2:15692", "rabbitmq3:15692"]
  - job_name: "producer"
    static_configs:
      - targets: ["host.docker.internal:8000"]
  - job_name: "consumer"
    static_configs:
      - targets:
          [
            "host.docker.internal:8001",
            "host.docker.internal:8002",
            "host.docker.internal:8003",
          ]
