version: '3'
services:
  rabbit1:
    image: rabbitmq:3-management
    hostname: rabbit1
    environment:
      - RABBITMQ_ERLANG_COOKIE='secretcookie'
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbit2:
    image: rabbitmq:3-management
    hostname: rabbit2
    environment:
      - RABBITMQ_ERLANG_COOKIE='secretcookie'
    ports:
      - "5673:5672"
      - "15673:15672"
