FROM python:3.10-slim

WORKDIR /app
ENV PYTHONPATH=/app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy full project code (ensuring the directory structure is preserved)
COPY . .

CMD ["python", "-m", "rabbitmq_project.scripts.run_producer"]