global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq1:15692']
        labels:
          instance: 'rabbit1'
          
      - targets: ['rabbitmq2:15692']
        labels:
          instance: 'rabbit2'
          
      - targets: ['rabbitmq3:15692']
        labels:
          instance: 'rabbit3'

  - job_name: 'rabbitmq-management'
    metrics_path: '/api/metrics'
    basic_auth:
      username: 'admin'
      password: 'admin123'
    static_configs:
      - targets: ['rabbitmq1:15672']
        labels:
          instance: 'rabbit1'
      - targets: ['rabbitmq2:15672']
        labels:
          instance: 'rabbit2'
      - targets: ['rabbitmq3:15672']
        labels:
          instance: 'rabbit3'
          
  - job_name: 'rabbitmq-client-metrics'
    static_configs:
      - targets: ['order_producer:9091', 'inventory_consumer:9091']
        labels:
          app: 'rabbitmq_client'